# Generated by Django 5.2.3 on 2025-07-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaignanalytics',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.emailtemplate'),
        ),
    ]
