# Generated by Django 5.2.3 on 2025-07-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_app', '0002_initial'),
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalytics',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='jobs_app.job'),
        ),
    ]
